name: Pharo CI

on:
  workflow_call:
    inputs:
      pharo-versions:
        description: "JSON array of versions, e.g. [13] or [12, 13]"
        required: true
        type: string

      export-image-name:
        description: "Name of the clean image to export (empty = no export)"
        required: false
        default: ""
        type: string

      metacello-baseline:
        description: "Metacello baseline to load"
        required: false
        default: "MyProject"
        type: string

      metacello-repository:
        description: "Metacello repository URL"
        required: false
        default: "github://myorg/myproject/src"
        type: string

      test-packages:
        description: "Packages to test"
        required: false
        default: ""
        type: string

      test-fail-on-error:
        description: "Fail the job if tests fail"
        required: false
        default: "true"
        type: string

      test-artifact-name:
        description: "Input only used by tests to generate unique artifact names"
        required: false
        type: string
        default: "test-results"


jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      PHARO_IMAGE_NAME: ${{ inputs.export-image-name != '' && inputs.export-image-name || 'Pharo' }}

    strategy:
      fail-fast: false

      matrix:
        pharo-version: ${{ fromJson(inputs.pharo-versions) }}

    steps:
      - uses: actions/checkout@v7

      - name: Setup Pharo
        uses: pharo-project/pharo-setup-gha@main
        with:
          version: ${{ matrix.pharo-version }}
          imageName: ${{ env.PHARO_IMAGE_NAME }}
      
      - name: Load project with Metacello (and save clean image)
        run: |
          # Force numeric conversion
          PHARO_VERSION=$(( ${{ matrix.pharo-version }} ))

          if [ "$PHARO_VERSION" -ge 14 ]; then
            PROJECT_NAME="${{ inputs.metacello-baseline }}"
          else
            PROJECT_NAME="BaselineOf${{ inputs.metacello-baseline }}"
          fi
          echo "Loding project $PROJECT_NAME"

          $PHARO --headless "$PHARO_IMAGE_NAME".image metacello \
            install ${{ inputs.metacello-repository }} "$PROJECT_NAME" \
            --save

      - name: Export clean image
        if: ${{ inputs.export-image-name != '' }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.export-image-name }}-${{ matrix.pharo-version }}
          path: |
            ${{ inputs.export-image-name }}.image
            ${{ inputs.export-image-name }}.changes
            *.sources

      - name: Run tests
        run: |
          $PHARO --headless "$PHARO_IMAGE_NAME".image test \
            --junit-xml-output \
            ${{ inputs.test-packages }} \
            ${{ inputs.test-fail-on-error == 'true' && '--fail-on-failure' || '' }}

      - name: Archive test results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: ${{ inputs.test-artifact-name }}-${{ matrix.pharo-version }}
          path: ./*.xml
