name: Non-regression Test Suite

on:
  pull_request:
  push:

permissions:
  checks: write
  contents: read

jobs:
  test-single:
    uses: ./.github/workflows/test-single.yml
  
  test-multi:
    uses: ./.github/workflows/test-multi.yml
  
  test-export:
    uses: ./.github/workflows/test-export.yml

  test-no-export:
    uses: ./.github/workflows/test-no-export.yml