name: Test Multi Version

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test-multi:
    strategy:
      matrix:
        pharo-version: [13, 14]
    
    uses: ./.github/workflows/pharo-test.yml
    with:
      pharo-version: ${{ matrix.pharo-version }}
      export-image-name: "TestImage"
      metacello-baseline: "Soup"
      metacello-repository: "src"
      test-packages: "Soup.*"
      test-artifact-name: "test-results-multi"

  assert-13:
    needs: test-multi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: TestImage-13
      - run: |
          test -f TestImage.image
          test -f TestImage.changes

      - uses: actions/checkout@v7
        with:
          sparse-checkout: .github
      - uses: actions/download-artifact@v7
        with:
          name: test-results-multi-13
      - uses: ./.github/actions/assert-xml-files
        name: Assert Test reports present
        with:
          path: .
          expected: "Soup-Tests-Core-Test.xml"

  assert-14:
    needs: test-multi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: TestImage-14
      - run: |
          test -f TestImage.image
          test -f TestImage.changes

      - uses: actions/checkout@v7
        with:
          sparse-checkout: .github
      - uses: actions/download-artifact@v7
        with:
          name: test-results-multi-14
      - uses: ./.github/actions/assert-xml-files
        name: Assert Test reports present
        with:
          path: .
          expected: "Soup-Tests-Core-Test.xml"
