name: Test Export

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/action.yml
    with:
      pharo-versions: "[14]"
      export-image-name: "ExportTest"
      metacello-baseline: "Soup"
      metacello-repository: "github://pharo-contributions/Soup/src"
      test-packages: "Soup.*"

  assert:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: ExportTest-14
      - run: |
          test -f ExportTest.image
          test -f ExportTest.changes
