name: Test No Export

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test-no-export:
    uses: ./.github/workflows/pharo-test.yml
    with:
      pharo-version: "14"
      metacello-baseline: "Soup"
      metacello-repository: "src"
      test-packages: "Soup.*"
      test-artifact-name: "test-results-no-export"

  assert:
    needs: test-no-export
    runs-on: ubuntu-latest
    steps:
      - name: Ensure no image artifact exists
        run: |
          ! gh run artifacts | grep -q "TestImage-14"
