name: Test Export

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/pharo-test.yml
    with:
      pharo-version: "14"
      export-image-name: "ExportTest"
      metacello-baseline: "Soup"
      metacello-repository: "src"
      test-packages: "Soup.*"
      test-artifact-name: "test-results-export"
      checkout-repository: "demarey/Soup"

  assert:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: ExportTest-14
      - run: |
          test -f ExportTest.image
          test -f ExportTest.changes
