name: Test Single Version

on:
  workflow_call:
  workflow_dispatch:

permissions:
  checks: write
  contents: read

jobs:
  test-single:
    uses: ./.github/workflows/pharo-test.yml
    with:
      pharo-version: "14"
      metacello-baseline: "Soup"
      metacello-repository: "src"
      test-packages: "Soup.*"
      test-artifact-name: "test-results-single"
      checkout-repository: "demarey/Soup"

  assert:
    needs: test-single
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          sparse-checkout: .github
      - uses: actions/download-artifact@v7
        with:
          name: test-results-single-14
      - uses: ./.github/actions/assert-xml-files
        name: Assert Test reports present
        with:
          path: .
          expected: "Soup-Tests-Core-Test.xml"