name: Test Multi Version

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test-multi:
    uses: ./.github/workflows/action.yml
    with:
      pharo-versions: "[13, 14]"
      export-image-name: "TestImage"
      metacello-baseline: "Soup"
      metacello-repository: "github://pharo-contributions/Soup/src"
      test-packages: "Soup.*"
      test-artifact-name: "test-results-multi"

  assert-13:
    needs: test-multi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: TestImage-13
      - run: |
          test -f TestImage.image
          test -f TestImage.changes

      - uses: actions/download-artifact@v7
        with:
          name: test-results-multi-13
      - name: debug
        run: ls -R
      - uses: actions/checkout@v7
        with:
          sparse-checkout: scripts/assert-xml-files.sh
          sparse-checkout-cone-mode: false
      - name: debug
        run: ls -R
      - name: Assert Test reports present
        run: bash -x ./scripts/assert-xml-files.sh . Soup-Tests-Core-Test.xml

  assert-14:
    needs: test-multi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: TestImage-14
      - run: |
          test -f TestImage.image
          test -f TestImage.changes

      - uses: actions/download-artifact@v7
        with:
          name: test-results-multi-14
      - name: debug
        run: ls -R
      - uses: actions/checkout@v7
        with:
          sparse-checkout: scripts/assert-xml-files.sh
          sparse-checkout-cone-mode: false
      - name: debug
        run: ls -R
      - name: Assert Test reports present
        run: ./scripts/assert-xml-files.sh . Soup-Tests-Core-Test.xml
